print catch "err [(throw "err "hello)]
