catch "error [(throw "error [this is an error])]
show error
