catch "err1 [throw "err2]
show error
